version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: circleci/golang:1.17  # Gunakan gambar yang sesuai dengan kebutuhan Anda
    steps:
      - run:
          name: Install hadolint
          command: |
            curl -fsSL -o hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            chmod +x hadolint
            sudo mv hadolint /usr/local/bin/
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: circleci/golang:1.17  # Gunakan gambar yang sesuai dengan kebutuhan Anda
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: circleci/golang:1.17  # Gunakan gambar yang sesuai dengan kebutuhan Anda
    steps:
      - checkout
      - run:
          name: Build and Push Image
          command: bash build_push_image_karsajobs.sh
