version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: circleci/golang:1.17
    steps:
      - run:
          name: Install hadolint
          command: |
            curl -fsSL -o hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            chmod +x hadolint
            sudo mv hadolint /usr/local/bin/
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Build and Push Image
          command: |
            # Add steps to build and push the Docker image

workflows:
  version: 2
  karsajobs-pipeline:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
